version: 3
services: 
  jenkinsmaster:
    image: "jenkinsci/blueocean"
    build: .
    ports:
      - "80:8080"
      - "50000:50000"
    volumes: 
      -  /var/lib/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
